FROM almalinux:9
#It can be override at the time of runtime
#CMD ["ping", "google.com"] 
#It can't be override at the time of tuntime.. if you give facebook.com it will not work
#ENTRYPOINT ["ping", "google.com"]
#For best outcomes use both CMD & ENTRYPOINT as below... CMD can be changed as per the requirement
CMD ["google.com"]
ENTRYPOINT ["ping"]